substitutions:
  name: "wmc-iot-nikolaus-esp"

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: "88ae8b5aa62702363d12036264178ce9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 0min

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  port: !secret mqtt_port
  birth_message:
    topic: "esp_Light_and_Sensor/status"
    payload: "online"
  topic_prefix: "esp32"
  discovery: true

captive_portal:

light:
  - platform: rgb
    name: "${name} RGB Light"
    id: rgblights
    red: r
    green: g
    blue: b

output:
  - platform: ledc
    pin: GPIO18
    id: r
  - platform: ledc
    pin: GPIO05
    id: g
  - platform: ledc
    pin: GPIO19
    id: b

i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  frequency: 400kHz

sensor:
  - platform: sgp30
    eco2:
      name: "${name} CO2 Level"
      accuracy_decimals: 1
    tvoc:
      name: "${name} TVOC Level"
      accuracy_decimals: 1
    address: 0x58
    update_interval: 1s
