substitutions:
  name: "wmc-nik-esp"

esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

logger:
  level: DEBUG

ota:
  - platform: esphome
    password: "88ae8b5aa62702363d12036264178ce9"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  reboot_timeout: 0min
  on_connect:
    - delay: 60s

web_server:
  port: 80

mqtt:
  broker: !secret mqtt_broker
  username: !secret mqtt_user
  password: !secret mqtt_password
  port: !secret mqtt_port
  birth_message:
    topic: "${name}/status"
    payload: "online"
  will_message:
    topic: "${name}/status"
    payload: "offline"
  discovery: true

captive_portal:

light:
  - platform: rgb
    name: "${name} RGB Light"
    id: rgblights
    red: r
    green: g
    blue: b
#    state_topic: "${name}/light/status"
#    command_topic: "${name}/light/set"

output:
  - platform: ledc
    pin: GPIO18
    id: r
  - platform: ledc
    pin: GPIO05
    id: g
  - platform: ledc
    pin: GPIO19
    id: b
