services:
  elasticsearch:
    image: docker.io/elastic/elasticsearch:8.15.0
    container_name: elasticsearch_8.15.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"
      cluster.routing.allocation.disk.threshold_enabled: false
      xpack.security.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
    volumes:
      - ./elasticsearch_8.15.0:/usr/share/elasticsearch/data
    networks:
      - efk_network

#    healthcheck:
#      test: [ "CMD", "curl", "-f", "http://localhost:9200" ]
#      interval: 10s
#      retries: 5
#      start_period: 30s
#      timeout: 10s
#
#  logstash:
#    image: docker.io/elastic/logstash:8.15.0
#    container_name: logstash
#    volumes:
#      - ./logstash/pipeline/gelf.conf:/usr/share/logstash/pipeline/logstash.conf
#    ports:
#      - "12201:12201/udp"
#      - "5000:5000"
#      - "9600:9600"
#    networks:
#      - elk_network
#    depends_on:
#      elasticsearch:
#        condition: service_healthy
  fluentd:
    image: docker.io/fluent/fluentd:v1.14.6-1
    container_name: fluentd
    ports:
      - "12201:12201/udp"
    volumes:
      - ./fluentd:/fluentd/etc
    networks:
      - efk_network
    depends_on:
      - elasticsearch

  kibana:
    image: docker.io/elastic/kibana:8.15.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - efk_network
    depends_on:
      - elasticsearch

  mqtt_logging_handler:
    image: openjdk:23-jdk-slim
    container_name: mqtt_logging_handler
    ports:
      - "8080:8080"
    environment:
      - QUARKUS_LOG_HANDLER_GELF_HOST=fluentd
    volumes:
      - ../Backend/mqtt_logging_handler/target:/app
      - ./mqtt_logging_handler/logs:/app/logs
    command: java -jar /app/quarkus-app/quarkus-run.jar
    networks:
      - efk_network
    depends_on:
      - fluentd
      - elasticsearch
      - kibana

  mqtt_for_home_assistant:
    image: eclipse-mosquitto
    container_name: mqtt_for_home_assistant
    ports:
      - "1883:1883"
    networks:
      - efk_network
      - docker_compose_home_assistant_network
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/log:/mosquitto/log

networks:
  efk_network:
    driver: bridge

  docker_compose_home_assistant_network:
    external: true