services:
  home_assistant:
    image: homeassistant/home-assistant:stable
    container_name: home_assistant
    ports:
      - "8123:8123"
    networks:
      - home_assistant_network
    volumes:
      - ./homeassistant:/config
    environment:
      - TZ=Europe/Berlin
    restart: always

networks:
  home_assistant_network:
    driver: bridge